sonar.projectKey=notik
sonar.projectName=Notik
sonar.projectVersion=1.0

sonar.host.url=http://notik-sonarqube:9000

sonar.sources=frontend/src,backend/src

sonar.tests=frontend/src,backend/tests

sonar.test.inclusions=frontend/src/**/*.test.ts,frontend/src/**/*.test.tsx,frontend/src/**/*.spec.ts,frontend/src/**/*.spec.tsx,backend/tests/**/*.test.ts,backend/tests/**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8